# TODO MultiheadAttention
# TODO PReLU
# TODO ReLU
# TODO ReLU6
# TODO RReLU
# TODO SELU
# TODO CELU
# TODO GELU
# TODO Sigmoid
# TODO Softplus
# TODO Softshrink
# TODO Softsign
# TODO Tanh
# TODO Tanhshrink
# TODO Threshold
# TODO Softmin
# TODO Softmax
# TODO Softmax2d
# TODO LogSoftmax
# TODO AdaptiveLogSoftmaxWithLoss
